config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_config:
    src: config
    dst: ~/.config
  f_picom.conf:
    src: picom.conf
    dst: ~/picom.conf
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  f_config.ini:
    src: config/polybar/config.ini
    dst: ~/.config/polybar/config.ini
  f_owm-key:
    src: owm-key
    dst: ~/.owm-key
profiles:
  archlinux:
    dotfiles:
    - d_config
    - f_picom.conf
    - d_polybar
    - f_config.ini
    - f_owm-key
